### ISSUE TITLE
Multiple match of datasets in a LOI, it's unclear the strategy used for selecting a dataset

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#12]
If multiple datasets match for a line of inquiry, it is unclear which ones are used. 

The simplest case is multiple matches for an input in a workflow. Does this trigger multiple workflows in parallel? Are the results aggregated somehow?

A more complicated case" let's say that a query retrieves 4 datasets from 2 cohorts, i.e., 2 pairs of hv/data to be used (the component has 2 inputs). How are the workflows run? Cross product? 1 to 1 execution?

At the moment everything is run by hitting a button, but there is little information on how that has happened.

**Comment by hvarg** [comment]
When quering a hypothesis the system will show you all possible convinations of the bindings, you must select a TLOI in that moment to run the workflow
