### ISSUE TITLE
Knowledge base does not work properly

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#41]
"Data" looks like this:
![image](https://user-images.githubusercontent.com/1520666/84439886-e5400b80-abed-11ea-8678-fb277ed2e41d.png)

Hypothesis is: 
![image](https://user-images.githubusercontent.com/1520666/84439915-f557eb00-abed-11ea-8f9c-60eb63102953.png)

LOI is:
![image](https://user-images.githubusercontent.com/1520666/84439972-13bde680-abee-11ea-9435-0932c36efc0e.png)

However, the hypothesis is never triggered. It looks like there is a problem with the KB, because I have tried other hypothesis removing the individuals in Data and they are still triggered.

**Comment by IKCAP** [comment]
As of now, I don't think the assertions in the Data tab are used if we are
using the wiki triple store as data store. Is this something that is
desired ?

**Comment by dgarijo** [comment]
Yes, because the wiki is only for retrieving datasets. In order to describe new hypothesis we need the data tab; otherwise we need to add individuals in the ontology every time, which is very inconvenient.

Actually, I have another hypothesis that was defined using individuals from the data tab, and keeps triggering
![image](https://user-images.githubusercontent.com/1520666/84528222-212dac00-ac94-11ea-9541-b7197912e707.png)

That :EffectSize... is an individual, which I created through the Data tab. Now that individual got erased, I don't know by whom, but things keep working on DISK. Same thing with :APOE4. It is not clear where all these things are declared, to be honest.

**Comment by hvarg** [comment]
The correct way to reference resources defined on assertions in a hypothesis is using the prefix `user:`
I've tested the example described for Daniel and is working now.
