### ISSUE TITLE
Add a note on data query to be able to explain the result table of the data query

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#60]
We need to be able to explain what is going in the table with the results of the dataset query to the wiki. 

After the meeting today, we need a new field to add a description in the LOI for this purpose.

**Comment by dgarijo** [comment]
Hernan claims this issue is done (waiting for a release)

**Comment by hvarg** [comment]
It's working with a modified version of the ontology, a less hackish way to fix it when https://github.com/KnowledgeCaptureAndDiscovery/DISK-Ontologies/issues/9 is done.
