### ISSUE TITLE
Convert meta-regression workflow into a metaworkflow

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#62]
Our current workflow for DISK includes a single workflow and no meta workflow.

In our example we aim to have a metaworkflow that corresponds to the workflow we already have.

The metaworkflow requires a hypothesis to review and a variable, which is not available in the current case. How to adapt the existing notion of meta-workflows to the one we need for the DISK use case?

**Comment by hvarg** [comment]
We need https://github.com/KnowledgeCaptureAndDiscovery/DISK-Ontologies/issues/10 to have the meta-workflows fully working.

**Comment by dgarijo** [comment]
Addressed by https://github.com/KnowledgeCaptureAndDiscovery/DISK-Ontologies/pull/11
