### ISSUE TITLE
Define semantics between DISK and Wiki

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#63]
We have to align the semantics between them, or we will not be able to use the ontologies we have defined for LOIs/terminology.

**Comment by dgarijo** [comment]
Right now we are using strings for matching concepts

**Comment by hvarg** [comment]
@haripriyad252 Can you take a look at the constraints defined on this file:
- [hypothesisQuestions.ttl](https://github.com/KnowledgeCaptureAndDiscovery/DISK/blob/master/portal/server/src/main/resources/hypothesisQuestions.ttl)

these constraints are useful to display valid options to the users when they are selecting a question hypothesis.
