### ISSUE TITLE
Bug: Hypothesis file is not being sent to WINGS

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#66]
Problem: New metaworkflow are not executing. DISK shows there is a match; but they won't be run in WINGS because the hypothesis file is missing.

**Comment by hvarg** [comment]
Fixed on https://github.com/KnowledgeCaptureAndDiscovery/DISK/commit/e9cf26e9c0ec9679e313ba60c2c74a86d457950f
