### ISSUE TITLE
Make the target wiki configurable for data queries

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#83]
We need to be able to define which external source we want the data to be imported from. We will have several wikis to choose from (right now dev and prod), this should be configurable in the LOI.

**Comment by hvarg** [comment]
We will match the data-query with its source on the LOI with a new property `:hasDataSource` from TLOI, LOI to string.

**Comment by hvarg** [comment]
@haripriyad252 can you add the property?

**Comment by haripriyad252** [comment]
Sure, I just added it. @dgarijo I created a PR, please review when you can.

**Comment by dgarijo** [comment]
Thanks @haripriyad252, but it also needs the documentation to be updated. Can you please add it?
