### ISSUE TITLE
Changes requested by Yolanda to the UI

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/DISK-legacy#84]
Yolanda reviewed the portal and requested the following changes:

In the front page:

- [x] Put the video at the bottom
- [x] Make the video smaller in the screen (if this is hard to do, never mind because it will not distract as much if it is at the bottom)
- [x] Change the top of the page to this (I realize we had not defined what NeuroDISK is): 
```
"What is NeuroDISK?

DISK is a general AI discovery system that automatically tests questions and hypotheses based on the data that it has access to.  NeuroDISK is the DISK site devoted to neuroscience, and in particular to the <ENIGMA consortium LINK: http://enigma.ini.usc.edu/>.”
```
- [ ] When I click on MyHypotheses, I get this URL: http://skc.isi.edu/disk-portal/#hypotheses/admin/test.  Why does it say “admin/test” at the end?  Same for the LOIs: http://skc.isi.edu/disk-portal/#lois/admin/test
- [x] I would like to have a separate tab “Hypotheses” at the top, and a separate tab “MyHypotheses” at the bottom.  “Hypotheses” should take me to the screen that you are now showing when I click on the plus sign to add a new hypothesis.  Once I create and save a new hypothesis, the hypothesis should appear under “MyHypotheses”.  Does that make sense?
- [x] In this page: http://skc.isi.edu/disk-portal/#lois/admin/test: it says “inquery” and it should say “inquiry”
- [x] In this page: http://skc.isi.edu/disk-portal/#terminology/admin/test:it says “Neuro DISK” and it should say “NeuroDISK”
- [x] the top sentence should say: “Hypotheses in NeuroDISK are expressed using a vocabulary of terms defined in the system, which can be easily extended by users.  The default vocabularies are defined in the following ontologies:”, and after the description of the ontologies it should say “Users can add new terms to the vocabularies as shown below."
- [ ] there should be a sentence describing each ontology.  
- [x] it looks like the ontology is only available as .ttl, so people will never click on it.  I would say more explicitly with two buttons: <access documentation> <download ontology in ttl format>
- [x] Replace the text for user defined terms with this: “The table below shows all the new terms defined by the user that are currently in the system. If you want to use a term to express a hypothesis and it is not defined in the ontologies above, you can add it to the vocabulary of the system by creating an entry on the last row of the table."
- [x] “Precentral” does not mean anything, it should be more specific (eg “PrecentralCortex”)
- [x] At the bottom of the page, instead of "Show metadata as turtle file” say “Show the formal representation of the new terms"
- [x] Ideally, I would like a new tab called “MyTerminology”, shown below “MyHypotheses”.  So the “Terminology” tab shows the ontologies that exist, and the “MyTerminology tab shows the new terms.

**Comment by hvarg** [comment]
Close because we opened https://github.com/KnowledgeCaptureAndDiscovery/DISK/issues/88
